//
// Created by Oleki on 19.01.2026.
//

#ifndef USB_INTERFACE_PROGRAMMING_RENDERER_H
#define USB_INTERFACE_PROGRAMMING_RENDERER_H


class Renderer {
};


#endif //USB_INTERFACE_PROGRAMMING_RENDERER_H